name = "Fusionpack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e668c6dfaa98e3d214fba5c632de205d7fcc729eb0a23ac01ad14aa62ebf6f61"

[versions]
fabric = "0.19.5"
minecraft = "1.21.1"
