name = "Fusionpack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "28973c97c24a39daebf482fc7503a7e2067b19edd7a60fe6159fcc1f8d127c29"

[versions]
fabric = "0.19.5"
minecraft = "1.21.1"
